### ISSUE TITLE
不用说英文哈，很不错的项目。有个bug指出一下望修改

### ISSUE THREAD

**Issue by yanyiqun001** [chinalwb/Android-Rich-text-Editor#1]
使用listnumberspan时， 光标在span修饰内容当中点删除，会使序号混乱。再就是选中多条span内容删除时会使内容混乱。

**Comment by chinalwb** [comment]
OK. 我尝试一下。如果重现了尽快修复哈。

**Comment by chinalwb** [comment]
我重现了，预计2月8日前解决。多谢提出问题。

**Comment by chinalwb** [comment]
解决了序号混乱的问题已经提交在master上。内容混乱的问题还需要一点时间。

**Comment by yanyiqun001** [comment]
我用了下最新的，还是有点问题，不好描述 能加个qq吗

**Comment by chinalwb** [comment]
OK. 329055754

**Comment by chinalwb** [comment]
[item_order_issues_from_yyq001.zip](https://github.com/chinalwb/Android-Rich-text-Editor/files/1697582/item_order_issues_from_yyq001.zip)

**Comment by chinalwb** [comment]
不好意思。这个问题我得再思考一下。需要晚些时间才能修复。

**Comment by chinalwb** [comment]
@yanyiqun001 刚提交了一个类，对提到的一个问题做了增强，光标在列表开始位置的处理。正在考虑选中一个区域进行删除和增加字符的处理。

**Comment by chinalwb** [comment]
@yanyiqun001 我提交了，有空你试一下，有问题请再提出来哈。谢谢。
