### ISSUE TITLE
Migration to AndroidX

### ISSUE THREAD

**Issue by Chris2011931** [chinalwb/Android-Rich-text-Editor#105]
Hi @chinalwb
I really appreciate your project. It would be nice if there would be an upgrade to support AndroidX. Thank you so much for the work that you have already put in this project.

**Comment by Amit2286658** [comment]
You can import the module in your project, and change the version of the glide library to the latest one which supports androidX. And it should be good to go

**Comment by Chris2011931** [comment]
ok, thank you. It worked.

**Comment by chinalwb** [comment]
Thank you guys!! Welcome fork and join me to make it better for others!
