### ISSUE TITLE
Change Icon colors on the toolbar

### ISSUE THREAD

**Issue by Esarve** [chinalwb/Android-Rich-text-Editor#115]
Hi I want to change the Icon colors on the toolbar to white. How to do that?

![toolbar](https://i.postimg.cc/brrxc29w/image.png)

**Comment by chinalwb** [comment]
Hi @Esarve  Great question!

Yes you can change it but, I'd say this is not that straightforward right now.

Here is the sample code takes `Bold` for example:

- Create a subclass of `ARE_ToolItem_Bold`. Override its `getView` method, and here you can just copy & paste the parent class's code, then change this line: ` imageView.setImageResource(R.drawable.my_bold);` with your own resource:
```

public class ARE_ToolItem_MyBold extends ARE_ToolItem_Bold {

    @Override
    public View getView(Context context) {
        if (null == context) {
            return mToolItemView;
        }
        if (mToolItemView == null) {
            ImageView imageView = new ImageView(context);
            int size = Util.getPixelByDp(context, 40);
            LinearLayout.LayoutParams params = new LinearLayout.LayoutParams(size, size);
            imageView.setLayoutParams(params);
            imageView.setImageResource(R.drawable.my_bold);
            imageView.bringToFront();
            mToolItemView = imageView;
        }

        return mToolItemView;
    }
}
```

And here is mine:

<img src="https://user-images.githubusercontent.com/1758864/84628256-de313a00-af1a-11ea-9321-6b7922a3b0bc.jpg" width="300" />

**Comment by Esarve** [comment]
Ok that will do too. Thanks!
