### ISSUE TITLE
Add youtube video

### ISSUE THREAD

**Issue by W7orld** [chinalwb/Android-Rich-text-Editor#116]
How can i add embed youtube video? using html iframe tag

**Comment by chinalwb** [comment]
@W7orld This needs to extend creating a new `ARE_ToolItem`. 

I worked out a sample for inserting a YouTube object:

![youtube](https://user-images.githubusercontent.com/1758864/85221335-b4c65180-b3e5-11ea-991c-c1d392a2c597.gif)

Generated HTML:
```
<html><body><p>A demo for YouTube:</p>
    <br>
    <p><iframe tag="youtube" title="Kotlin tutorial" src="https://www.youtube.com/watch?v=7HPfx6i-bvA" /></p>
    <br>
    <br>
    </body></html>
```

You can find the code with this commit: https://github.com/chinalwb/Android-Rich-text-Editor/commit/a0da9b3a4ecd08b221f198aad618028e2446ff61

**Comment by W7orld** [comment]
How can i using it in my project?

**Comment by chinalwb** [comment]
First make sure the implementation looks fine to you, you can see it if you build the latest code, then copy the codes in the commit to your project.

**Comment by W7orld** [comment]
> 
> 
> First make sure the implementation looks fine to you, you can see it if you build the latest code, then copy the codes in the commit to your project.

Got it.. Thanks
