### ISSUE TITLE
AreClickStrategy Not working

### ISSUE THREAD

**Issue by chaitu14** [chinalwb/Android-Rich-text-Editor#117]
Even though I have implemented customised  ARtextview its works as by default behavior mentioned code not working. can 
   you help me with that

        are_TextView.setClickStrategy(new AreClickStrategy() {
            @Override
            public boolean onClickAt(Context context, AreAtSpan atSpan) {

                return false;
            }

            @Override
            public boolean onClickImage(Context context, AreImageSpan imageSpan) {
                imageSpan.
                return false;
            }

            @Override
            public boolean onClickUrl(Context context, URLSpan urlSpan) {
                Toast.makeText(context,"Its clicked",Toast.LENGTH_SHORT).show();

                return true;
            }

            @Override
            public boolean onClickVideo(Context context, AreVideoSpan videoSpan) {
                return false;
            }
        });

**Comment by chinalwb** [comment]
Sorry for the late response!
Thanks for pointing out the issue!

Actually [@Lucio King](https://github.com/LeisurelyLucio) had told me about the issue but sorry I didn't get a chance to have it included till now.

0.1.10 has been released, and it should work now!

For your case, your code is absolutely correct, (it's fault at my code), so pls try out with the new version. Thanks!

**Comment by chinalwb** [comment]
@chaitu14  Please reopen if it doesn't work for you!
