### ISSUE TITLE
请问如何插入网络图片？

### ISSUE THREAD

**Issue by ejwdhr** [chinalwb/Android-Rich-text-Editor#13]

**Comment by chinalwb** [comment]
@ejwdhr 好问题。我加到这个版本的todo 了。排在了 视频之后 音频之前。大概2~3周吧。敬请关注。谢谢提出。

**Comment by ejwdhr** [comment]
我已经自己修改了一部分，但是会出现这个情况，图中加载的图片被遮盖了一部分，edittext重新获取焦点然后删除部分空白后图片恢复显示正常，我是否需要在插入图片后重新绘制edittext或是重新测量高度？该如何进行？（图片无法上传。。。尝试了好多次）

**Comment by chinalwb** [comment]
@ejwdhr 我提交了这个插入网络图片的功能在master上。

demo 视频如下：
Demo for inserting an image from internet:
----
 ![image](https://github.com/chinalwb/are/blob/master/ARE/demo/image_from_internet_demo.gif)

欢迎持续关注。

多谢提出问题。

Thanks.
