### ISSUE TITLE
有一个闪退bug

### ISSUE THREAD

**Issue by jixiongxu** [chinalwb/Android-Rich-text-Editor#15]
在选中图片后有闪退，第一张没问题，加载第二或第三张就闪退了。我觉得是不是控件内存消耗太大导致内存溢出

**Comment by chinalwb** [comment]
多谢反馈，我瞧一瞧。

**Comment by chinalwb** [comment]
@jixiongxu  请问您是用真机测试还是模拟器？

**Comment by chinalwb** [comment]
@jixiongxu 已解决。提交到了master. 烦请有空的试试再帮忙测试。
原因是当图片宽度过小时程序放大处理时出错。
再次感谢提出问题。

**Comment by chinalwb** [comment]
Close了。有问题你再打开. @jixiongxu 
Thanks
