### ISSUE TITLE
Cannot found class

### ISSUE THREAD

**Issue by AbdullahProgrammer426351** [chinalwb/Android-Rich-text-Editor#158]
I have imported the project as mentioned in documentation but it is not showing In project
I have added this line to my build.gradle file : 
implementation 'com.github.chinalwb:are:0.1.7'

**Comment by chinalwb** [comment]
Did you use **jcenter** in your project?

**Comment by AbdullahProgrammer426351** [comment]
> Did you use **jcenter** in your project?

This is resolved 👍👍
