### ISSUE TITLE
A clear guideline needed!

### ISSUE THREAD

**Issue by subbirhosain27** [chinalwb/Android-Rich-text-Editor#17]
Would you mind giving a clear guideline to add the editor in my project? Thank you

**Comment by shahzadakram67** [comment]
same

**Comment by chinalwb** [comment]
Of course, in fact I am waiting for guys open such an issue. Give me a bit time to write some document. Thanks for your patience.

**Comment by chinalwb** [comment]
@subbirhosain27 @shahzadakram67 
Checkout [this](https://github.com/chinalwb/Android-Rich-text-Editor/blob/master/Usage.md), hope it is helpful for you to get start.

BTW, ARE is still in progress and you see its version number is 0.1.0, so please be careful before using in your project as I could be not able to help with all issues immediately. Of course I welcome you fork and fix issues if you run into during your usage with ARE.

Thanks.

**Comment by subbirhosain27** [comment]
after importing the module as you have said choose '3. Module Dependency', in the popup window nothing is showing.

**Comment by chinalwb** [comment]
Any error when doing step 1 and 2?

**Comment by ohenepee** [comment]
I'm also getting the same issue as @subbirhosain27 

**Nothing to show** after you select the __3. Module Dependency__

**Comment by chinalwb** [comment]
@ohenepee let me double check.

**Comment by chinalwb** [comment]
@ohenepee @subbirhosain27 I am sorry that you ran into such issues.

I confirmed and it seems like there is bug about importing modules into Android Studio with the latest version. I updated Android Studio and reproduced the issue. Mine AS version is 3.1, 173.4670197

I updated the [guideline](https://github.com/chinalwb/Android-Rich-text-Editor/blob/master/Usage.md), maybe you can try out the new steps, let me know if it still doesn't work for you.

Thank you for reporting this!

**Comment by chinalwb** [comment]
I've updated readme and more info with samples, please check if necessary, let me know if you need more about ARE. Thanks.
