### ISSUE TITLE
真正集成到项目中去之后，才发现类与类之间耦合真的太严重了，改都不好改。。强烈希望大神后面能解耦

### ISSUE THREAD

**Issue by lrain-lv** [chinalwb/Android-Rich-text-Editor#21]

**Comment by chinalwb** [comment]
@lrain-lv 多谢反馈。能举例说明你用的哪些功能需要改造吗？

**Comment by lrain-lv** [comment]
我是把你的项目集成公共库里面，我在主module里面需要用你的图片点击，展示什么的都是我自己来实现的，但是你的是已经集成好的，所以我就写了个接口，从editor->toolebar->are-imgstyle一层一层传下去，还有其他地方使用这个功能可能就不需要加粗 斜体之类的功能 我就要重新改了 建议能把toolbar提出来

**Comment by lrain-lv** [comment]
大神还有个问题，就是上传了图片之后 我点击图片然后光标到了图片那里 然后图片是居中的样式 这个要怎么改呢

**Comment by lrain-lv** [comment]
我想要点击图片之后直接光标到下一行，。 我是不是要改样式呢

**Comment by lrain-lv** [comment]
好的 多谢大神
