### ISSUE TITLE
能出个实现原理文章、调用过程的文章、或者说代码结构文章吗，我在看are的时候，对一些类作用还不是很清晰

### ISSUE THREAD

**Issue by yovenny** [chinalwb/Android-Rich-text-Editor#23]
...

**Comment by chinalwb** [comment]
@yovenny 我最近在做Toolbar和ToolItem的重构，等完成的时候 这些类结构和继承关系可能会稍微改变下，但我会在使用文档中写明各模块之间的关系。

这里我可以大致说一下，供你参考。

1.`AREditor` （RelativeLayout） 包含了`AREditText` （EditText） 和`ARE_Toolbar` （LinearLayout） 
2. `AREditText` 里面有一个 `TextWatcher`, 当用户输入文字 或删除文字的时候回触发这里的回调方法，目前主要起作用的是 `afterTextChanged` 方法
3. `ARE_Toolbar` 里面是一个个的ImageView， 比如粗体，斜体，插入图片等各个样式的图标，在ARE里面叫`IARE_Style` (styles 那个package里面的类是各个样式的实现)
4. 输入框中文字改变的时候 `afterTextChanged` 方法会依次调用所有注册的`IARE_Style`的`applyStyle`方法
5. 各个样式的`applyStyle`方法需要设定合适的span(`spans` package里有各个实现类)参数

不止您一位提出这个关于文档不清晰的问题了，我在改进 （无奈最近工作一直较忙，近一个月多来更新慢了 不过不会对已有功能停止维护）

如有问题继续沟通，欢迎fork 然后一起开发。

谢谢。

**Comment by chinalwb** [comment]
我更新了readme, 有问题可以再提出来哈。谢谢。
