### ISSUE TITLE
Force closed ARE app

### ISSUE THREAD

**Issue by roboticvn** [chinalwb/Android-Rich-text-Editor#24]
Some time, ARE app was forced close. 
Below is error log I got:
`08-06 14:57:07.079  6261  6261 E AndroidRuntime: FATAL EXCEPTION: main
08-06 14:57:07.079  6261  6261 E AndroidRuntime: Process: com.chinalwb.are.demo, PID: 6261
08-06 14:57:07.079  6261  6261 E AndroidRuntime: java.lang.IndexOutOfBoundsException: setSpan (-1 ... -1) starts before 0
08-06 14:57:07.079  6261  6261 E AndroidRuntime:        at android.text.SpannableStringBuilder.checkRange(SpannableStringBuilder.java:1314)
08-06 14:57:07.079  6261  6261 E AndroidRuntime:        at android.text.SpannableStringBuilder.setSpan(SpannableStringBuilder.java:680)
08-06 14:57:07.079  6261  6261 E AndroidRuntime:        at android.text.SpannableStringBuilder.setSpan(SpannableStringBuilder.java:672)
08-06 14:57:07.079  6261  6261 E AndroidRuntime:        at com.chinalwb.are.styles.ARE_ListBullet.changeListNumberSpanToListBulletSpan(ARE_ListBullet.java:462)
08-06 14:57:07.079  6261  6261 E AndroidRuntime:        at com.chinalwb.are.styles.ARE_ListBullet.access$000(ARE_ListBullet.java:22)
08-06 14:57:07.079  6261  6261 E AndroidRuntime:        at com.chinalwb.are.styles.ARE_ListBullet$1.onClick(ARE_ListBullet.java:68)
08-06 14:57:07.079  6261  6261 E AndroidRuntime:        at android.view.View.performClick(View.java:6897)
08-06 14:57:07.079  6261  6261 E AndroidRuntime:        at android.view.View$PerformClick.run(View.java:26100)
08-06 14:57:07.079  6261  6261 E AndroidRuntime:        at android.os.Handler.handleCallback(Handler.java:789)
08-06 14:57:07.079  6261  6261 E AndroidRuntime:        at android.os.Handler.dispatchMessage(Handler.java:98)
08-06 14:57:07.079  6261  6261 E AndroidRuntime:        at android.os.Looper.loop(Looper.java:164)
08-06 14:57:07.079  6261  6261 E AndroidRuntime:        at android.app.ActivityThread.main(ActivityThread.java:6944)
08-06 14:57:07.079  6261  6261 E AndroidRuntime:        at java.lang.reflect.Method.invoke(Native Method)
08-06 14:57:07.079  6261  6261 E AndroidRuntime:        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327)
08-06 14:57:07.079  6261  6261 E AndroidRuntime:        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374)`

I don't know exactly when error occur. However, for example, you can reproduce the issue as following:
1> Build ARE app -> run on real device
2> Select all -> remove
3> Use ListNumber to write some list
4> Click ListBullet -> app FC

**Comment by chinalwb** [comment]
Reproduced, I'll fix, thanks for reporting.

**Comment by chinalwb** [comment]
@roboticvn I checked in a fix for this, could you please help confirm if resolved when you have time? Thanks very much for pointing out the issue.

**Comment by roboticvn** [comment]
Very quickly :)). I have checked and the issue is fixed. Thank you :D

**Comment by chinalwb** [comment]
Thanks for your testing feedback. :)
