### ISSUE TITLE
Change font size incorrect 

### ISSUE THREAD

**Issue by roboticvn** [chinalwb/Android-Rich-text-Editor#25]
I see that you are setting default font size is 18. 
When I change the font size to other value (for example 24) and write some text. If I back to font size 18, all of the text before also change the font size to 18

**Comment by chinalwb** [comment]
Reproduced, I'll fix, thanks for reporting.

**Comment by chinalwb** [comment]
Resolved. [Checked in ](https://github.com/chinalwb/Android-Rich-text-Editor/commit/96b82cd5ad596f039e28f292085afae0be07fd1f)

**Comment by chinalwb** [comment]
@roboticvn I checked in the fix, you may give it a try, thanks again for pointing out the issue.

**Comment by roboticvn** [comment]
The issue is fixed :)

**Comment by chinalwb** [comment]
Thank you for the feedback :)
