### ISSUE TITLE
问个简单问题

### ISSUE THREAD

**Issue by bingely** [chinalwb/Android-Rich-text-Editor#35]
在哪里可以修改默认的字体大小？当是纯文字时，在哪里设置fontsize 属性。我知道在html.java中，怕改错里面逻辑了

这个库很棒

**Comment by chinalwb** [comment]
纯文字？您是指 TextView 还是 EditText?

**Comment by bingely** [comment]
EditText,默认输出的是<div>&#22909;&#32416;&#32467;&#23601;&#26159;<span style="font-size:22px";>ddd</span></div>。     我想在&#22909;&#32416;&#32467;&#23601;&#26159;前面也加fontsize属性

**Comment by chinalwb** [comment]
噢 我好像理解错了 您是指导出的html里面的 对吧

**Comment by bingely** [comment]
<div>&#22909;&#32416;&#32467;&#23601;&#26159;<span style="font-size:22px";>ddd</span></div>

**Comment by bingely** [comment]
![image](https://user-images.githubusercontent.com/11975992/44318521-1a072f80-a469-11e8-83a4-04962fc66464.png)

**Comment by chinalwb** [comment]
您截屏里 ddd 的size 是 22px 您的需求是改变 div 里面的字体大小吗

**Comment by bingely** [comment]
默认没给字体大小时也给赋值fontsize，现在输出是<div> &XXX

**Comment by bingely** [comment]
纯文字（没有样式）的输入如何判断，
![image](https://user-images.githubusercontent.com/11975992/44318610-af0a2880-a469-11e8-8a55-8970db119fe7.png)  这是手动设置字体大小有类型判断

**Comment by chinalwb** [comment]
如果您需要为 `&#22909;&#32416;&#32467;&#23601;&#26159;前面也加fontsize属性`, 我建议：
1. 选中这些需要设定font size的文字，加上字体样式
2. 如果您最终导出的html是希望在网页上显示，建议您修改下全局的CSS样式，也就是在saveHtml的时候 把您希望的默认字体以CSS的方式加在html里面

**Comment by chinalwb** [comment]
如果您需要为每个div都加上默认的 font-size 那么是可以的。因为纯文字本身不是span 所以无法在对span进行判断的分支里做修改。 可以在往 StringBuilder out 里面追加div的地方 加上默认的字体大小。
比如 Html.java -> L353：

```
           if (needDiv) {
                out.append("<div /*这里加font size*/").append(elements).append(">");
            }
```

**Comment by bingely** [comment]
谢谢，你写的很棒

**Comment by chinalwb** [comment]
不客气。我想问下您方便告知您APP的名字吗？或是您APP应用的行业。谢谢。

**Comment by bingely** [comment]
还没正式上线这个功能，教育的。就是想实现这个图文混排的功能

**Comment by chinalwb** [comment]
谢谢您告知。
