### ISSUE TITLE
这段字符串在你那个空格预览页面显示不出来图片？其它格式都行

### ISSUE THREAD

**Issue by bingely** [chinalwb/Android-Rich-text-Editor#36]
`<div align="left"><font style="font-size:16.000000;color:#333333">快来救救我</font></div><div><img src="http://img.ckeyedu.com/UALNLCZIBJ1534752090.jpg" style="width:100%;height:auto"/></div>
`

**Comment by chinalwb** [comment]
![are_screenshot](https://user-images.githubusercontent.com/1758864/44331638-a7b04280-a49c-11e8-8fd3-852d1faf18fa.png)
我测试结果是这样。

**Comment by chinalwb** [comment]
Closed. Please reopen if the problem still exists for you.
