### ISSUE TITLE
0.1.2 版 glide 冲突...

### ISSUE THREAD

**Issue by LinXueyuanStdio** [chinalwb/Android-Rich-text-Editor#48]
```
AGPBI: {"kind":"error","text":"Program type already present: com.bumptech.glide.GeneratedRequestManagerFactory","sources":[{}],"tool":"D8"}
```

**Comment by chinalwb** [comment]
没太懂这个消息是什么意思啊

**Comment by ckckchen** [comment]
我也有个问题，GlideAPPModule被写成了final，如果我想register component 只能自己新写一个GlideAPPModule. 但是在使用GlideAPP的时候会出现，Cast Exception on GlideRequests .
请问有什么办法解决吗？

**Comment by chinalwb** [comment]
> 我也有个问题，GlideAPPModule被写成了final，如果我想register component 只能自己新写一个GlideAPPModule. 但是在使用GlideAPP的时候会出现，Cast Exception on GlideRequests .
> 请问有什么办法解决吗？

看来是个普遍的问题。应该是我的demo中的场景太简单了?

我在一个demo程序里面，依赖了Glide, 然后用Glide加载了网图，同时依赖了 ARE，也可以正常工作。

我再抽时间看吧。。不好意思。。

**Comment by LinXueyuanStdio** [comment]
把build文件夹删掉重新构建一次就行了
