### ISSUE TITLE
New Design

### ISSUE THREAD

**Issue by Yasujizr** [chinalwb/Android-Rich-text-Editor#5]
![android rich text](https://user-images.githubusercontent.com/36993664/38454930-003f1874-3a79-11e8-812e-439c48ab3dd1.jpg)

Hi,

I have studied your work and I think a new design will make you more visible. I designed for you, I hope you like it and you want to use it. If you want to reach me, you can look at the my profile. I can give you all the formats of the design free. If you want a change please specify.

*Andorid in A and Fountain Pen combine*

**Comment by chinalwb** [comment]
Really appreciate your work!

The icons look great, and they match what the app current features.

However I am planning to make the final App to be something like a notebook. Where users can write and view previous notes. Also I may want to change the main color to blue color scheme from current orange.

So if you can design an icon for this, that would be fantastic. Thank you in advance.

**Comment by Yasujizr** [comment]
Thank you,

I will work on it.

**Comment by Yasujizr** [comment]
![are](https://user-images.githubusercontent.com/36993664/38524381-01f51d1e-3c57-11e8-86b0-9e34455a1845.jpg)

**Comment by chinalwb** [comment]
@Yasujizr Great icons! I like the left one.

**Comment by Yasujizr** [comment]
What size and format do you want? I will send you.

**Comment by chinalwb** [comment]
I'll check and let you know. Thank you.

**Comment by chinalwb** [comment]
@Yasujizr Sorry for the delay. Here is the size spec:
48 × 48 (mdpi)
72 × 72 (hdpi)
96 × 96 (xhdpi)
144 × 144 (xxhdpi)
192 × 192 (xxxhdpi)
512 × 512 (Google Play store)

All in png format.

Thanks.

**Comment by Yasujizr** [comment]
You can access from this link.

https://drive.google.com/open?id=1vRGEXhDFuNUn3ZGtAjrEAdlTjsg20eKJ

If you have any problems or need another logo, you can write to me.
Thank u.

**Comment by chinalwb** [comment]
Thanks, I applied the icons and I will add your name to the project.
