### ISSUE TITLE
新功能，视频上传

### ISSUE THREAD

**Issue by LZQL** [chinalwb/Android-Rich-text-Editor#7]
你好，您能否支持和知乎一样的添加视频上传功能，我想这会是个很强大的编辑器

**Comment by chinalwb** [comment]
@LZQL 多谢提供需求。计划2018-04-30（0.0.7）完成嵌入视频功能。并提供上传回调接口。

**Comment by chinalwb** [comment]
尚未发布，不过基本版本出来了。
 ![image](https://github.com/chinalwb/are/blob/master/ARE/demo/video_demo.gif)

**Comment by chinalwb** [comment]
@LZQL 我close了。有问题你再open.
Thanks
