### ISSUE TITLE
How to Add Toolbar Item for FontColor

### ISSUE THREAD

**Issue by WyangMiss** [chinalwb/Android-Rich-text-Editor#70]
How to Add Toolbar Item Font Foregound/Background Color in ARE_ToolbarDefault

**Comment by chinalwb** [comment]
Sorry these two features are not yet implemented in the `ARE_ToolbarDefault`.

**Comment by chinalwb** [comment]
Stay tuned

**Comment by chinalwb** [comment]
Finished font color, you can checkout the latest code to check.

https://github.com/chinalwb/Android-Rich-text-Editor/commit/7388ec5e8f73a778dc7cb56ede48ec507a47c55e

**Comment by chinalwb** [comment]
![screenshot-0 1 6](https://user-images.githubusercontent.com/1758864/58300784-91ae2480-7e16-11e9-8374-90ab114e9653.png)
I had it done in 0.1.6, posted the release.
