### ISSUE TITLE
How to upload Images from Storage

### ISSUE THREAD

**Issue by usamex** [chinalwb/Android-Rich-text-Editor#71]
Hello, I liked this rich text but I couldn't upload an image to the edittext. (I use ARE_EDITTEXT and ARE_DEFAULT_TOOLBAR) should I use imageStrategy for this or something else? I saw the demo and it only uploads an image from the web. Not the image that I selected. But on AREditor, it can upload the selected image. What should I do to upload an image using AREditText and ARE_Toolbar_Default?

**Comment by chinalwb** [comment]
![Screenshot_20190527-144845](https://user-images.githubusercontent.com/1758864/58400777-a4329300-808e-11e9-8307-218ce836b180.jpg)

ARE provides the interface/callback to upload the image but it doesn't do the upload itself because it doesn't know upload the image to what server.

ARE_Toolbar_Default has a demo feature about selecting a local image and show back in the editing area like above. Do you see the same?

**Comment by usamex** [comment]
Yes, I saw this pop-up and I am able to select the image. But after that, It doesn't put the image to the ARE_Edit_Text. It gives this error:
E/SpannableStringBuilder: SPAN_EXCLUSIVE_EXCLUSIVE spans cannot have a zero length

**Comment by chinalwb** [comment]
Hi, did you do the testings on the embedded emulator of Android Studio? Or what's your Android model and OS version? I can insert the image on my phone and emulator.

**Comment by usamex** [comment]
I use Huawei Mate 10 with Android Pie (9)

**Comment by chinalwb** [comment]
Sorry I cannot reproduce the issue on Android 9 emulator.

![WX20190527-173721](https://user-images.githubusercontent.com/1758864/58411082-18c4fc00-80a6-11e9-8244-679adf1cee7a.png)


Can you please try out the latest APK?
https://github.com/chinalwb/Android-Rich-text-Editor/releases/download/0.1.6/ARE_20190524_0.1.6.apk

**Comment by usamex** [comment]
Here is the video for my issue:
https://youtu.be/T_CWlLHQyqg
I want to add the Image that I selected.

**Comment by usamex** [comment]
I've solved the problem, It was my fault sorry. I forgot to create onActivityResult function.

**Comment by chinalwb** [comment]
Thank you for the update.

**Comment by brindhamaran235** [comment]
Hi 
   I have same issue and i create the onActivityResult function but local image not upload
