### ISSUE TITLE
Multiple dex files

### ISSUE THREAD

**Issue by Amit2286658** [chinalwb/Android-Rich-text-Editor#84]
Multiple dex files error occurs when used with projects that uses androidX, please migrate the library files from android support-v4 to androidX.

**Comment by chinalwb** [comment]
Thanks for pointing out this issue, I'll consider and migrating.

**Comment by Amit2286658** [comment]
I've imported the library as a project module, and changed the dependency from suport to AndroidX, therefore I'm closing this issue
