### ISSUE TITLE
How can I Hide some of tool bar buttons?

### ISSUE THREAD

**Issue by naveen-nuveda** [chinalwb/Android-Rich-text-Editor#87]
Hi, 
I don't want to use Video, Image, @, and Href support to AREEditor as per my app functionality.

How can I disable it? 
Is there any way to set true or false for this?

**Comment by chinalwb** [comment]
Unfortunately no. All features are wrapped into AREditor by default, that's why I introduced `IARE_Toolbar` with which you can customize the toolbar by yourself.

So you'll want to clone the code and do the customization yourself.

Thanks for be interesting in ARE.
