### ISSUE TITLE
[Overlap text]

### ISSUE THREAD

**Issue by Hieuntdz** [chinalwb/Android-Rich-text-Editor#91]
Hello bro. thanks for your great editor view.
I'm using your library but I found a problem in your project.
this problem make text overlap each other. 
Hear is the youtube video description that problem.

https://www.youtube.com/watch?v=nrcTyiCjs9c&feature=youtu.be&fbclid=IwAR1bW1SENCNvOVVRJcIjPB0qiF4jnBXlz7YessvjwI7xHpkIFkBfMHnpMm0

**Comment by chinalwb** [comment]
Thanks for reporting the issue I will check.

**Comment by chinalwb** [comment]
> Hello bro. thanks for your great editor view.
> I'm using your library but I found a problem in your project.
> this problem make text overlap each other.
> Hear is the youtube video description that problem.
> 
> https://www.youtube.com/watch?v=nrcTyiCjs9c&feature=youtu.be&fbclid=IwAR1bW1SENCNvOVVRJcIjPB0qiF4jnBXlz7YessvjwI7xHpkIFkBfMHnpMm0

Inside `AREditText.java`, there is a method like this:
```
	/**
	 * Needs this because of this bug in Android O:
	 * https://issuetracker.google.com/issues/67102093
	 */
	public void useSoftwareLayerOnAndroid8() {
		if (Build.VERSION.SDK_INT == Build.VERSION_CODES.O) {
			this.setLayerType(View.LAYER_TYPE_SOFTWARE, null);
		}
	}
```

Could you please try invoking this method from `init` and then give it a shot again?

I tested in this way and it worked for me just now.

AFAIK TextView.java on Android O has a few issues, this is one of them, I still cannot find a good approach to resolve.

Thanks again for report this issue. I will continue to find a proper approach (when I have time to do so ...)

**Comment by Hieuntdz** [comment]
Yes. It work fine sir

**Comment by Hieuntdz** [comment]
> > Hello bro. thanks for your great editor view.
> > I'm using your library but I found a problem in your project.
> > this problem make text overlap each other.
> > Hear is the youtube video description that problem.
> > https://www.youtube.com/watch?v=nrcTyiCjs9c&feature=youtu.be&fbclid=IwAR1bW1SENCNvOVVRJcIjPB0qiF4jnBXlz7YessvjwI7xHpkIFkBfMHnpMm0
> 
> Inside `AREditText.java`, there is a method like this:
> 
> ```
> 	/**
> 	 * Needs this because of this bug in Android O:
> 	 * https://issuetracker.google.com/issues/67102093
> 	 */
> 	public void useSoftwareLayerOnAndroid8() {
> 		if (Build.VERSION.SDK_INT == Build.VERSION_CODES.O) {
> 			this.setLayerType(View.LAYER_TYPE_SOFTWARE, null);
> 		}
> 	}
> ```
> 
> Could you please try invoking this method from `init` and then give it a shot again?
> 
> I tested in this way and it worked for me just now.
> 
> AFAIK TextView.java on Android O has a few issues, this is one of them, I still cannot find a good approach to resolve.
> 
> Thanks again for report this issue. I will continue to find a proper approach (when I have time to do so ...)

**Comment by Hieuntdz** [comment]
> > Hello bro. thanks for your great editor view.
> > I'm using your library but I found a problem in your project.
> > this problem make text overlap each other.
> > Hear is the youtube video description that problem.
> > https://www.youtube.com/watch?v=nrcTyiCjs9c&feature=youtu.be&fbclid=IwAR1bW1SENCNvOVVRJcIjPB0qiF4jnBXlz7YessvjwI7xHpkIFkBfMHnpMm0
> 
> Inside `AREditText.java`, there is a method like this:
> 
> ```
> 	/**
> 	 * Needs this because of this bug in Android O:
> 	 * https://issuetracker.google.com/issues/67102093
> 	 */
> 	public void useSoftwareLayerOnAndroid8() {
> 		if (Build.VERSION.SDK_INT == Build.VERSION_CODES.O) {
> 			this.setLayerType(View.LAYER_TYPE_SOFTWARE, null);
> 		}
> 	}
> ```
> 
> Could you please try invoking this method from `init` and then give it a shot again?
> 
> I tested in this way and it worked for me just now.
> 
> AFAIK TextView.java on Android O has a few issues, this is one of them, I still cannot find a good approach to resolve.
> 
> Thanks again for report this issue. I will continue to find a proper approach (when I have time to do so ...)

Hello sir. Call useSoftwareLayerOnAndroid8() function  work for this bug. 
But when call this function and if i add AREditText inside a scrollView. 
when i paste a long text to AREditText . this view will display error( show a white blank view.)

**Comment by chinalwb** [comment]
I know this issue but sorry I have no solution for it right now, if you can help check that'll be great. Thanks.
