### ISSUE TITLE
How to apply multiple style in one word without space?

### ISSUE THREAD

**Issue by wangxianming315** [chinalwb/Android-Rich-text-Editor#96]
For example, I need to implement 2 styles(Bold, Underline) in one word 'HelloWorld' without space.
Hello as Bold and World as Underline.
Is this possible?
I tested your demo app and when I try to click style button, it changes full word(without space) style.
I hope to hear feedback from you.
Thanks.

**Comment by chinalwb** [comment]
No problem, what your actions were like? Actually it’s easy. Just select BOLD style then type in HELLO, then unselect  BOLD but select UNDERLINE then type in world.

Or you can type in helloworld first then select hello then hit on BOLD, do the same to world part, then I think you’ll get what you want to see. 

Try and let me know if it works for you.

Thanks.

**Comment by wangxianming315** [comment]
Hello, thanks for your help. The second one works. But the first one doesn't. This is my problem.
When I select BOLD and type 'Hello', the 'Hello' is bold. And then unselect BOLD and select UNDERLINE, type 'w' then the 'Hello' is now UNDERLINE not BOLD. So the entire word is now UNDERLINE.
I want to apply multiple style while typing without space.
Regards.

**Comment by chinalwb** [comment]
Got it I’ll check and get back to you.

**Comment by wangxianming315** [comment]
Please let me know if you can help me on this. Thanks.

**Comment by chinalwb** [comment]
Apologize for my late reply 

I was busy with working recently hope I can have some time for it tonight.

**Comment by wangxianming315** [comment]
Thank you very much.

**Comment by satapon148** [comment]
This problem is happen because the style is apply to the whole "word" as I can see it happen when there's any auto complete word when typing. Try separate the word or complete it and edit them later work just fine.

**Comment by wangxianming315** [comment]
Hi @satapon148 . thanks for looking into this issue.
You are right and the style is applied to whole word. But I need to apply multiple style in one word while typing.
Is this not possible?

**Comment by satapon148** [comment]
yes it is possible to do that
1. type the thing you want and accept the auto complete in that onscreen keyboard
2. now the device/app should see it as just a line of text go ahead and highlight where you need it to be style.
3. repeat until you get your desire result
I belive this issue is coming from android or it's keyboard want to get what you want to type then pass all off it to the app and the app just understand all of it as single text input so they just apply to the whole word. I didn't look into the source code but belive the owner might get an idea what's happening

**Comment by wangxianming315** [comment]
Yes. I can get desired result by repeating to apply style to sub-selection of whole text after type full text.
But this is not what I want. 
What I want is, for example in word 'ABC', I want to set 'A' as Bold and 'BC' as normal character.
So first I will select Bold style and type 'A', it is ok now.
Second I will unselect Bold and type 'B'. then the 'A' is changed to un-bold.
This is my problem.

**Comment by chinalwb** [comment]
@wangxianming315 Sorry I tried but didn't reproduce.
What's your phone? Can you try it on the android studio simulator to see if you can reproduce?

**Comment by chinalwb** [comment]
![2019-09-16 21-23-00 2019-09-16 21_23_31](https://user-images.githubusercontent.com/1758864/64961509-4093d600-d8c8-11e9-8c1f-64dcfd642e46.gif)

**Comment by chinalwb** [comment]
Here is another video for **hello**_world_ ![2019-09-16 21-26-22 2019-09-16 21_26_50](https://user-images.githubusercontent.com/1758864/64961768-c57eef80-d8c8-11e9-81c8-1beed43c2e6b.gif)

**Comment by wangxianming315** [comment]
Wow. This is what I want. My phone is HUAWEI.
Let me test again.

**Comment by chinalwb** [comment]
I also tested on a Mi-5S, works like exactly the same.

**Comment by chinalwb** [comment]
FYI: I have such code in `AREditText.java`

```java
this.setInputType(EditorInfo.TYPE_CLASS_TEXT | EditorInfo.TYPE_TEXT_FLAG_MULTI_LINE
				| EditorInfo.TYPE_TEXT_FLAG_NO_SUGGESTIONS);
```

**Comment by chinalwb** [comment]
@satapon148 Thanks for stepping in. :)

**Comment by wangxianming315** [comment]
I have tested Nexus 5X and Pixel 2 simulator.
It works on Nexus 5x but not Pixel 2.
Do you have any idea about this?

**Comment by chinalwb** [comment]
Sorry no... I tried on Pixel 2 simulator just now, it works as well.

How about your HUAWEI?

**Comment by wangxianming315** [comment]
Then I think this is because I am using old version.
Are you testing latest commit?

**Comment by chinalwb** [comment]
I am testing based on the latest code of master.

**Comment by wangxianming315** [comment]
What is the API version of your Pixel 2 simulator?
Mine is Android 9, API 28
My HUAWEI phone is Android 8.0, API 26
Nexus 5 simulator is API 25.

**Comment by chinalwb** [comment]
Pixel 2: API 26
Nexus 5: API 26
MI-5s: API 24

**Comment by wangxianming315** [comment]
To test the demo project, should I open the ARE root folder?

**Comment by chinalwb** [comment]
<img width="776" alt="Screen Shot 2019-09-16 at 10 50 59 PM" src="https://user-images.githubusercontent.com/1758864/64968293-7dfe6080-d8d4-11e9-8913-9d555ec1647a.png">

Do you mean this?

**Comment by chinalwb** [comment]
Try using `implementation project(':are')` instead of `implementation 'com.github.chinalwb:are:0.1.6'`

**Comment by chinalwb** [comment]
Hitting the sack..  I'll try to response to you ASAP for your future comments.

Thanks a lot for your interests on ARE.

**Comment by wangxianming315** [comment]
Now I am able to run the project.

Ok. thanks for your effort for me.
Have a good dream :)

**Comment by wangxianming315** [comment]
So in my experience, it works on Pixel 2 API 26 but not working on Pixel 2 API 28.
Please check it on Pixel 2 API 28 simulator when you are available.
Thanks.

**Comment by chinalwb** [comment]
Okay thanks for the debugging.

Btw what’s your time zone?

**Comment by wangxianming315** [comment]
I am in Shenyang. :) GMT+8. I usually work late. lol.

**Comment by chinalwb** [comment]
Really! I saw your profile just now. I usually sleep early but wake up late :)

**Comment by wangxianming315** [comment]
Please let me know when you have any good news. :)

**Comment by chinalwb** [comment]
I’ll try to reproduce on SDK 28 tonight.

**Comment by wangxianming315** [comment]
Thank you.

**Comment by chinalwb** [comment]
Reproduced on SDK 28. I'll check and fix.

**Comment by wangxianming315** [comment]
Thank you!

**Comment by chinalwb** [comment]
Do you mind the auto-complete feature of the keyboard?

I found I disabled that before so it works on pre 28 versions.

The disable setting doesn't work on Android P, thus you see the bug.

**Comment by chinalwb** [comment]
I think you have been able to run the ARE project on your local, right?

If yes, please try to add this to `AREditText.java#init()`, on line 97: 

```java
		this.setInputType(EditorInfo.TYPE_CLASS_TEXT | EditorInfo.TYPE_TEXT_FLAG_MULTI_LINE
				| EditorInfo.TYPE_TEXT_FLAG_NO_SUGGESTIONS | EditorInfo.TYPE_TEXT_VARIATION_VISIBLE_PASSWORD);
		Typeface typeface = Typeface.DEFAULT;
		this.setTypeface(typeface);
```

**Comment by wangxianming315** [comment]
Yes. I am trying it now.

**Comment by wangxianming315** [comment]
Wow. Now it works on both API 26 and 28.
The auto-complete feature of the keyboard is now disabled on Android P too.

**Comment by chinalwb** [comment]
Yes, I believe I had tried to have that included but failed somehow, after that, I didn't get a chance to look into again ...

Hope it works for you.

**Comment by wangxianming315** [comment]
Ok. Now I think everything works well as expected.
I am going to close this issue now.
Thank you very much for your effort.
You are very smart guy.
Have a good night. :)

**Comment by chinalwb** [comment]
Thanks for your kind words, I had tried hardly to find some guy as stupid as I, but now, I give up.

Good morning!
